name: ci
on:
  pull_request:
  push:
    branches:
      - main
      - master

jobs:
  Test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
        compiler:
          - gcc-11
          - gcc-12
          - gcc-13
          - llvm-16
          # you can specify the version after `-` like `llvm-13.0.0`.
        CMAKE_GENERATOR:
          - "Ninja Multi-Config"
        include:
          - compiler: gcc-11
            toolchain: gcc-11
          - compiler: gcc-12
            toolchain: gcc-12
          - compiler: gcc-13
            toolchain: gcc-13
          - compiler: llvm-16
            toolchain: ci-clang

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          compiler: ${{ matrix.compiler }}
          vcvarsall: ${{ contains(matrix.os, 'windows') }}
          cmake: true
          ninja: true
          task: true
          cppcheck: true
          clangtidy: true # instead of `true`, which chooses the default version, you can pass a specific version.

      - name: Build
        run: |
          ./bld compile TOOLCHAIN=${{ matrix.toolchain }}

      - name: Test
        run: |
          ./bld test TOOLCHAIN=${{ matrix.toolchain }}

      - name: Test-ASAN
        run: |
          ./bld test TOOLCHAIN=${{ matrix.toolchain }} CONFIG=Asan

      - name: Test-TSAN
        run: |
          ./bld test TOOLCHAIN=${{ matrix.toolchain }} CONFIG=Tsan
